version: "3"
services:
    # we're using an implementation of nginx that autogenerates configurations
    # https://github.com/jwilder/nginx-proxy
  nginx-proxy:
    container_name: puzzlepieces_proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DHPARAM_GENERATION=0

  web:
    container_name: puzzlepieces_backend
    image: puzzlepieces_backend
    build: ../
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    expose:
     - 8000
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - VIRTUAL_PROTO=uwsgi
    env_file:
      - development.env
    depends_on:
      - db
    # networks:
    #   - frontend
    #   - backend
  db:
    container_name: puzzlepieces_db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - db-dev.env
    volumes:
      - mysql_db:/var/lib/mysql
    # networks:
    #   - backend

# networks:
#   frontend:
#     driver: bridge
#   backend:
#     driver: bridge

volumes:
  mysql_db: