name: Build Docker Image

on:
  pull_request:
    paths-ignore:
      - 'ops/**'
      - 'scripts/**'
      - '.github/**'
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build image
      run: docker build . --file Dockerfile --tag puzzlepieces:$(git rev-parse --short "$GITHUB_SHA")
