name: Development Deploy

on:
  push:
    branches:
      - develop
      - master

jobs:
    publish_latest:
      runs-on: ubuntu-latest
      env:
        TAG: docker.pkg.github.com/corridors-of-time-transcription/puzzlepieces/puzzlepieces:latest
        REGISTRY: docker.pkg.github.com
        USERNAME: corridors-of-time-transcription
      steps:
      - uses: actions/checkout@v2

      - name: login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY --username $USERNAME --password-stdin

      - name: build image
        run: docker build . --file Dockerfile --tag ${TAG}

      - name: publish image
        run: docker push ${TAG}

    deploy_latest:
      needs: publish_latest
      runs-on: ubuntu-latest
      name: deploy latest on development instance with ansible
      env:
        REGISTRY: docker.pkg.github.com
        USERNAME: corridors-of-time-transcription
      steps:
        - uses: actions/checkout@v2
        
        - name: setup python
          uses: actions/setup-python@v1.1.1
          with:
            python-version: 3.8
        
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install ansible==2.9.2 requests

        - name: setup ssh-agent
          uses: webfactory/ssh-agent@v0.2.0
          with:
            ssh-private-key: ${{ secrets.DEV_DEPLOY_SSH_PRIVATEKEY }}

        - name: setup ssh known_hosts
          run: echo ${{ secrets.DEV_DEPLOY_SSH_HOSTKEY }} > ~/.ssh/known_hosts

        - name: run playbooks/configure
          run: |
            ansible-playbook ./ops/ansible/playbooks/compose/configure.yml -i ${{ secrets.DEV_DEPLOY_URL }}, -u ${{ secrets.DEV_DEPLOY_USER }}

        - name: setup ansible vault
          run: echo '${{ secrets.ANSIBLE_VAULT_PASS_DEV }}' > ./.ansible-vault-pass

        - name: run playbooks/deploy
          run: |
            ansible-playbook ./ops/ansible/playbooks/compose/deploy.yml -i ${{ secrets.DEV_DEPLOY_URL }}, -u ${{ secrets.DEV_DEPLOY_USER }} --vault-password-file ./.ansible-vault-pass --extra-vars "varsfile=dev.yml docker_registry=$REGISTRY docker_user=$USERNAME docker_pass=${{ secrets.GITHUB_TOKEN }}"